# Generated by Django 5.1.14 on 2025-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp3", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="tel_number",
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="contact",
            name="fees",
            field=models.IntegerField(default=0, help_text="Consultation fee"),
        ),
        migrations.AddField(
            model_name="contact",
            name="hospital",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contact",
            name="rating",
            field=models.FloatField(default=0.0, help_text="1–5 rating"),
        ),
        migrations.AddField(
            model_name="contact",
            name="speciality",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
