# Generated by Django 5.1.14 on 2025-11-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp3", "0002_remove_contact_profession_remove_contact_tel_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="hospital",
        ),
        migrations.AddField(
            model_name="contact",
            name="education",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="contact",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="fees",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="contact",
            name="speciality",
            field=models.CharField(max_length=200),
        ),
    ]
